#!/usr/bin/env python

import xstalker, xstalker.stats
import logging

filters = [
        ("coding", lambda ctx: ctx.win_class == "konsole"),
        ("unknown", lambda _: True)
        ]

xstalker.start_daemon (
        log_file = None,
        log_level = logging.DEBUG,
        db_file = "/tmp/aaa",
        filters = filters
        )

